data <- read.csv("/Users/SIMONA/Documents/Datafest/updated.csv", header = TRUE, sep = ',')
data$nutrition[is.na(data$nutrition)] <- "Okay"
data$nutrition <- factor(data$nutrition, levels = c("Okay", "Poor", "Excellent"))
data$sleephours <- cut(data$sleephours, c(0, 3, 6, 9, 14.5, Inf))
levels(data$sleephours) <- c("No Sleep", "Deprived", "Adequate", "Plenty", "Coma")
data$sleephours <- relevel(data$sleephours, ref = "Adequate")
levels(data$sleephours)
str(data)
model <- lm(fatigue~ irritability + sleephours + sleepquality + pain + nutrition, data = data)
summary(model)
anova(model)
data$prediction <- predict(model)
data$residuals <- model$residuals
par(mfrow = c(2,2))
plot(model)
write.csv(data,"/Users/SIMONA/Documents/Datafest/model.csv")